name: autoheal
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - openai
      - python-dotenv
      - pandas
      - tqdm
      - networkx
      - requests
